warp-cli add-excluded-host *rsjst.com
warp-cli add-excluded-host *zgfxrc.cn
warp-cli add-excluded-host *edpfm.cn
warp-cli add-excluded-host *dspfm.cn
warp-cli add-excluded-host *cepfm.cn
warp-cli add-excluded-host *qq.com
warp-cli add-excluded-host *zhihu.com
warp-cli add-excluded-host *zhihuishu.com
warp-cli add-excluded-host *zhimg.com
warp-cli add-excluded-host *zhuihd.com
warp-cli add-excluded-host *bing.com
warp-cli add-excluded-host *alipay.com
warp-cli add-excluded-host *alibaba.com
warp-cli add-excluded-host *alicdn.com
warp-cli add-excluded-host *alipay.com
warp-cli add-excluded-host *amap.com
warp-cli add-excluded-host *dingtalk.com
warp-cli add-excluded-host *youku.com
warp-cli add-excluded-host *xiami.com
warp-cli add-excluded-host *apple.co
warp-cli add-excluded-host *apple.com
warp-cli add-excluded-host *apple-cloudkit.com
warp-cli add-excluded-host *appstore.com
warp-cli add-excluded-host *cdn-apple.com
warp-cli add-excluded-host *icloud.com
warp-cli add-excluded-host *icloud-content.com
warp-cli add-excluded-host *me.com
warp-cli add-excluded-host *baidubcr.com
warp-cli add-excluded-host *baidupan.com
warp-cli add-excluded-host *baidupcs.com
warp-cli add-excluded-host *yunjiasu-cdn.net
warp-cli add-excluded-host *biliapi.com
warp-cli add-excluded-host *biliapi.net
warp-cli add-excluded-host *bilibili.com
warp-cli add-excluded-host *bilibili.tv
warp-cli add-excluded-host *toutiao.com
warp-cli add-excluded-host *iqiyi.com
warp-cli add-excluded-host *iqiyipic.com
warp-cli add-excluded-host *jd.com
warp-cli add-excluded-host *jdpay.com
warp-cli add-excluded-host *outlook.com
warp-cli add-excluded-host *office365.com
warp-cli add-excluded-host *microsoft.com
warp-cli add-excluded-host *163.com
warp-cli add-excluded-host *126.com
warp-cli add-excluded-host *163yun.com
warp-cli add-excluded-host *lofter.com
warp-cli add-excluded-host *youdao.com
warp-cli add-excluded-host *netease.com
warp-cli add-excluded-host *paypal.com
warp-cli add-excluded-host *paypal.me
warp-cli add-excluded-host *sina.com
warp-cli add-excluded-host *weibo.com
warp-cli add-excluded-host *weibocdn.com
warp-cli add-excluded-host *weico.cc
warp-cli add-excluded-host *myapp.com
warp-cli add-excluded-host *myqcloud.com
warp-cli add-excluded-host *qqmail.com
warp-cli add-excluded-host *servicewechat.com
warp-cli add-excluded-host *tencent.com
warp-cli add-excluded-host *tencent-cloud.com
warp-cli add-excluded-host *tencent-cloud.net
warp-cli add-excluded-host *tenpay.com
warp-cli add-excluded-host *wechat.com
warp-cli add-excluded-host *115.com
warp-cli add-excluded-host *douban.com
warp-cli add-excluded-host *doubanio.com
warp-cli add-excluded-host *douyu.com
warp-cli add-excluded-host *dxycdn.com
warp-cli add-excluded-host *jianshu.com
warp-cli add-excluded-host *jianshu.io
warp-cli add-excluded-host *lanzous.com
warp-cli add-excluded-host *maoyan.com
warp-cli add-excluded-host *maoyun.tv
warp-cli add-excluded-host *hdslb.com

